
name: test-output-jobs
run-name: ${{ github.actor }} is learning to use job's outputs 
on: [push, label, create, delete]
jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.step1.job1 }}
        steps:
            - id: step1
              run: echo "job1=output" >> "$GITHUB_OUTPUT"
    job2:
        runs-on: ubuntu-latest
        needs: job1 # Important to be allowed to access the output of job1
        steps:
            - env:
                JOB1_OUTPUT: $ {{ needs.job1.outputs.output1 }}
              run: echo $JOB1_OUTPUT
            - env:
                JOB1_OUTPUT: $ {{ needs.job1.outputs.output1 }}
              if: needs.job1.outputs.output1 == 'job2'
              run: echo "Will never be displayed"
        