name: file_type_dependent_activation
run-name: ${{ github.actor }} test triggering depending path and/or file type

on: 
    push: 
        paths:  
            - app/**
            - '**.js'

jobs:
    js_files_job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "doing stuff related to js files only" 
                