name: test-dependant-jobs_with_alway_running_job
run-name: ${{ github.actor }} is learning dependant job with alway running one;
on: [push]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "job1"
    failing_job:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - run: dfsf 
    not_running_job:
        runs-on: ubuntu-latest
        needs: [job1, failing_job]
        steps:
            - run: echo "Never run"
    running_job_whatever_happens: 
        runs-on: ubuntu-latest
        if: ${{ always() }}
        needs: [job1, failing_job]
        steps:
            - run: echo "Always run after job1 & failing job"
        